@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.hanwei233.enchanterpearl;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;